#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: tanish kumar | Course: Open Source Software

echo "========================================"
echo "   Open Source Manifesto Generator"
echo "========================================"
echo "Answer three questions to generate your personalized statement."
echo ""

# Interactive User Input
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

# Date and Filename Setup
DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

# --- Logic: Composing the Paragraph ---
# Using string concatenation and command substitution
MANIFESTO_TEXT="On this day, $DATE, I declare my commitment to the open source movement. 
By utilizing tools like $TOOL, I recognize that $FREEDOM is the foundation of 
true innovation. In the spirit of global collaboration, I pledge to build 
$BUILD and share it freely with the community, just as Git revolutionized 
how we track and share our collective progress."

# --- Writing to File ---
# '>' overwrites the file, '>>' would append to it
echo "OFFICIAL OPEN SOURCE MANIFESTO" > "$OUTPUT"
echo "--------------------------------" >> "$OUTPUT"
echo "$MANIFESTO_TEXT" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Generated by: $(whoami)" >> "$OUTPUT"

# --- Alias Concept Demonstration (Comment Only) ---
# To create a shortcut for this script, you could add this to your .bashrc:
# alias mymanifesto='./manifesto_generator.sh'

echo "----------------------------------------"
echo "SUCCESS: Manifesto saved to $OUTPUT"
echo "----------------------------------------"

# Displaying the final result
cat "$OUTPUT"
echo "========================================"
